fixtures:
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib'
    apt: 'https://github.com/puppetlabs/puppetlabs-apt'
    inifile: 'https://github.com/puppetlabs/puppetlabs-inifile'
    grafana: 'https://github.com/voxpupuli/puppet-grafana'
    archive: 'https://github.com/voxpupuli/puppet-archive'
    systemd: 'https://github.com/voxpupuli/puppet-systemd'
    yumrepo:
      repo: 'https://github.com/puppetlabs/puppetlabs-yumrepo_core'
      puppet_version: ">= 6.0.0"
    telegraf: 'https://github.com/voxpupuli/puppet-telegraf'
    facts: 'https://github.com/puppetlabs/puppetlabs-facts'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent'
    provision: 'https://github.com/puppetlabs/provision'
    puppet_metrics_collector: 'https://github.com/puppetlabs/puppetlabs-puppet_metrics_collector'
    puppet_conf: 'https://github.com/puppetlabs/puppetlabs-puppet_conf'
    deploy_pe: 'https://github.com/jarretlavallee/puppet-deploy_pe'
    ruby_task_helper: 'https://git@github.com/puppetlabs/puppetlabs-ruby_task_helper'
    cron_core: 'https://github.com/puppetlabs/puppetlabs-cron_core'
    bootstrap: 'https://github.com/puppetlabs/puppetlabs-bootstrap'
